spring:
  datasource:
    url: jdbc:postgresql://${DB_SN_HOST:localhost}:5432/socialnetwork
    username: ${DB_SN_USERNAME:admin}
    password: ${DB_SN_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/change-log/db.changelog-master.xml
    enabled: false
#spring.datasource.url: jdbc:h2:mem:testdb