apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploymenyt
  labels:
    app: app
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: app
  template:
    metadata:
      labels:
        app: app
    spec: 
      containers:
      - name: app
        image: sergs82/socialnetwork-jar:latest
        ports:
        - containerPort: 8080
        env:
          - name: TZ
            value: "UTC"
          - name: DB_SN_PORT
            value: "5432"
          - name: DB_SN_HOST
            valueFrom:
              configMapKeyRef: 
                name: database-config
                key: DB_SN_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000